models/ProductOut.php
<?php

namespace app\models;

use Yii;
use app\models\QuantityType;
use app\models\ProductType;
use app\models\Potency;
use app\models\Product;
use app\modules\users\models\Users;
/**
 * This is the model class for table "product_out".
 *
 * @property int $id
 * @property int $buyer_user_id buyer user id
 * @property int $seller_user_id self user id
 * @property int $product_type_id
 * @property int $potency_id
 * @property int $quantity_type_id
 * @property int $product_id
 * @property int $total_qty
 * @property string $notes
 * @property int $status
 * @property string $date_time
 */
class ProductOut extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'product_out';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [[ 'buyer_user_id', 'seller_user_id', 'product_type_id', 'potency_id', 'quantity_type_id', 'product_id', 'total_qty'], 'required'],
            [['status', 'buyer_user_id', 'seller_user_id', 'product_type_id', 'potency_id', 'quantity_type_id', 'product_id', 'total_qty'], 'integer'],
            [['notes'], 'string'],
            [['date_time'], 'safe'],
            [['total_qty'], 'string', 'max' => 1],
            [['id'], 'unique'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'buyer_user_id' => 'Buyer User',
            'seller_user_id' => 'Seller User',
            'product_type_id' => 'Product Type',
            'potency_id' => 'Potency',
            'quantity_type_id' => 'Quantity Type',
            'product_id' => 'Product',
            'total_qty' => 'Total Qty',
            'notes' => 'Notes (Optional)',
            'status' => 'Status',
            'date_time' => 'Date Time',
        ];
    }
  public function getBuyerUser()
    {
        return $this->hasOne(Users::className(), ['id' => 'buyer_user_id']);
    }	
	
    public function getSellerUser()
    {
        return $this->hasOne(Users::className(), ['id' => 'seller_user_id']);
    }  
	
    public function getPotency()
    {
        return $this->hasOne(Potency::className(), ['id' => 'potency_id']);
    }
		
    public function getProducttype()
    {
        return $this->hasOne(ProductType::className(), ['id' => 'product_type_id']);
    }
		
    public function getQuantitytype()
    {
        return $this->hasOne(QuantityType::className(), ['id' => 'quantity_type_id']);
    }		
	
    public function getProduct()
    {
        return $this->hasOne(Product::className(), ['id' => 'product_id']);
    }
}

controllers/ProductoutController.php
<?php

namespace app\controllers;

use Yii;
use app\models\ProductOut;
use app\models\ProductOutSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Indent;
use app\models\ProductIn;
/**
 * ProductoutController implements the CRUD actions for ProductOut model.
 */
class ProductoutController extends Controller
{
	public $enableCsrfValidation = false;
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all ProductOut models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ProductOutSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionSmyorder()
    {
        $searchModel = new ProductOutSearch();
		$searchModel->seller_user_id=Yii::$app->user->id;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('sindex', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
	
    public function actionBmyorder()
    {
        $searchModel = new ProductOutSearch();
		$searchModel->buyer_user_id=Yii::$app->user->id;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('bindex', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    /**
     * Displays a single ProductOut model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new ProductOut model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new ProductOut();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
			'indent' => null,
        ]);
    }
	
    public function actionCreateorder($inid)
    {
        $model = new ProductOut();

		$indent = Indent::findOne($inid);
		
		if (Yii::$app->request->post()) {
			$model->load(Yii::$app->request->post());
			$model->indent_id=$inid;
			$model->seller_user_id=Yii::$app->user->id;
			$model->buyer_user_id=$indent->buyer_user_id;
			$model->product_type_id=$indent->product_type_id;
			$model->potency_id=$indent->potency_id;
			$model->quantity_type_id=$indent->quantity_type_id;
			$model->product_id=$indent->product_id;


			if ($model->save()) {
			    // Indent Status Change to Order Create
				$indent->status=2;
			    $indent->save(false);
				return $this->redirect(['index']);
			}
		}
        return $this->render('create', [
            'model' => $model,
            'indent' => $indent,
        ]);
    }

    /**
     * Updates an existing ProductOut model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
		$inid=$model->indent_id;
		$indent = null;
		if($inid>0){
			$indent = Indent::findOne($inid);
		}

        if ($model->load(Yii::$app->request->post()) && $model->save()) {

            $status=$indent->status;
			if ($model->status==1) $status=2;
			if ($model->status==2) $status=3;
			if ($model->status==3) $status=4;

			// Indent Status Change to Order Create
			$indent->status=$status;
			$indent->save(false);
			return $this->redirect(['index']);
        }

        return $this->render('update', [
            'model' => $model,
            'indent' => $indent,
        ]);
    }

    /**
     * Deletes an existing ProductOut model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the ProductOut model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return ProductOut the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ProductOut::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Product;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;

class SiteController extends Controller
{
	
	 public $enableCsrfValidation = false;
	 public $layout = 'ashirvad';
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

	public function actionProduct() {
		$products = [];
		if (isset($_POST['depdrop_all_params'])) {
			$parents = $_POST['depdrop_all_params'];

			if ($parents != null) {
				$product_type_id = 0;
				$potency_id = 0;
				$quantity_type_id = 0;
				$product_type_id = $parents['product_type_id'];
				$potency_id = $parents['potency_id'];
				$quantity_type_id = $parents['quantity_type_id'];
				// $out = self::getSubCatList($cat_id); 
				// the getSubCatList function will query the database based on the
				// cat_id and return an array like below:
				// [
				//    ['id'=>'<sub-cat-id-1>', 'name'=>'<sub-cat-name1>'],
				//    ['id'=>'<sub-cat_id_2>', 'name'=>'<sub-cat-name2>']
				// ]

				
				$products=Product::find()
						->where(['product_type_id' =>$product_type_id])
						->andWhere(['potency_id' =>$potency_id])
						->andWhere(['quantity_type_id' =>$quantity_type_id])
						->orderBy('id')
						->asArray()
						->all();

				$selected  = null;
				$out  = null;
				if ($products != null && count($products) > 0) {
					$selected = '';
					foreach($products as $i => $product) {
						$out[] = ['id' => $product['id'], 'name' => $product['name']];
						if ($i == 0) {
							$selected = $product['id'];
						}
					}
					// Shows how you can preselect a value
					echo Json::encode(['output' => $out, 'selected'=>$selected]);
					return;
				}

			}
		}
		echo Json::encode(['output'=>$products, 'selected'=>'']);
	}
 
    /**
     * Login action.
     *
     * @return Response|string
     */
	

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionEvents()
    {
        return $this->render('events');
    }  
	public function actionPortfolio()
    {
        return $this->render('portfolio');
    } 
	public function actionAbout()
    {
        return $this->render('about');
    }

}

views/productout/_form.php
<?php


use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;
use kartik\date\DatePicker;
use app\models\QuantityType;
use app\models\ProductType;
use app\models\Potency;
use app\modules\users\models\Users;
use yii\helpers\ArrayHelper;
use kartik\widgets\DepDrop;
/* @var $this yii\web\View */
/* @var $model app\models\ProductOut */
/* @var $form yii\widgets\ActiveForm */
?>
    <?php $product_type_id=ArrayHelper::map(ProductType::find()->orderBy('id')->asArray()->all(),'id', 'name');; ?>
    <?php $potency_id=ArrayHelper::map(Potency::find()->orderBy('id')->asArray()->all(),'id', 'name'); ?>
    <?php $quantity_type_id=ArrayHelper::map(QuantityType::find()->orderBy('id')->asArray()->all(),'id', 'name');; ?>
	<?php $buyer_user_id=ArrayHelper::map(Users::find()->andWhere(['or',['is_buyer_seller'=>1],['is_buyer_seller'=>3]])->orderBy('id')->asArray()->all(),'id', 'username');; ?>
    <?php $status=['1'=>'Order Created','2'=>'Order shipped']; ?>
	
<div class="product-out-form">

    <?php $form = ActiveForm::begin(); ?>

	<div class="col-lg-8">
	<?php if((Yii::$app->controller->action->id=='createorder') or (Yii::$app->controller->action->id=='update' and $model->indent_id>0)){ ?>  
	<div class="row">
				<div class="receipt-header receipt-header-mid">
					<div class="col-xs-12 col-sm-12 col-md-12" style="background: #f0f0f0;" >
						<h2>Order Info</h2>
						<div class="receipt-right">
							<p><b>Buyer Name :</b> <?php echo $indent->buyerUser->username; ?></p>
							<p><b>Product Type :</b> <?php echo $indent->producttype->name; ?></p>
							<p><b>Potency :</b> <?php echo $indent->potency->name; ?></p>
							<p><b>Quantity Type :</b> <?php echo $indent->quantitytype->name; ?></p>
							<p><b>Product :</b> <?php echo $indent->product->name; ?></p>
						</div>
					</div>
				</div>
            </div>
				
	<?php 
	$model->total_qty=$indent->total_qty;
	$model->notes=$indent->notes;
	if(Yii::$app->controller->action->id=='createorder'){
		$model->status=$indent->status;	
	}
	
	?>
	
	<?php }else{  ?>
	
			<?= $form->field($model, 'buyer_user_id')->widget(Select2::classname(), [
				'data' => $buyer_user_id,
				'options' => ['placeholder' => 'Select Buyer ...'],
				'pluginOptions' => [
					'allowClear' => true
				],
			]); ?>
			<?php // $form->field($model, 'seller_user_id')->textInput() ?>

			<?= $form->field($model, 'product_type_id')->widget(Select2::classname(), [
				'data' => $product_type_id,
				'options' => ['placeholder' => 'Select Product Type ...','id' => 'product_type_id'],
				'pluginOptions' => [
					'allowClear' => true
				],
			]); ?>

			<?= $form->field($model, 'potency_id')->widget(Select2::classname(), [
				'data' => $potency_id,
				'options' => ['placeholder' => 'Select Potency ...','id' => 'potency_id'],
				'pluginOptions' => [
					'allowClear' => true
				],
			]); ?>

			<?= $form->field($model, 'quantity_type_id')->widget(Select2::classname(), [
				'data' => $quantity_type_id,
				'options' => ['placeholder' => 'Select Quantity Type ...','id' => 'quantity_type_id'],
				'pluginOptions' => [
					'allowClear' => true
				],
			]); ?>

			<?php
				// Child # 3
				echo $form->field($model, 'product_id')->widget(DepDrop::classname(), [
					'options' => ['placeholder' => 'Select Product ...','id'=>'product_id'],
					'pluginOptions'=>[
						'depends'=>['product_type_id', 'potency_id', 'quantity_type_id'],
						'placeholder'=>'Select Product...',
						'url'=>Url::to(['/site/product'])
					]
				]);
			?>
<?php } ?>

			<?= $form->field($model, 'total_qty')->textInput(['type' => 'number']) ?>
			
			<?= $form->field($model, 'status')->widget(Select2::classname(), [
				'data' => $status,
				'options' => ['placeholder' => 'Select Status ...'],
				'pluginOptions' => [
					'allowClear' => true
				],
			]); ?>
	
			<?= $form->field($model, 'notes')->textarea(['rows' => 6]) ?>

        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/productout/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ProductOutSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="product-out-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'buyer_user_id') ?>

    <?= $form->field($model, 'seller_user_id') ?>

    <?= $form->field($model, 'product_type_id') ?>

    <?= $form->field($model, 'potency_id') ?>

    <?php // echo $form->field($model, 'quantity_type_id') ?>

    <?php // echo $form->field($model, 'product_id') ?>

    <?php // echo $form->field($model, 'total_qty') ?>

    <?php // echo $form->field($model, 'notes') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'date_time') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/productout/bindex.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $searchModel app\models\ProductOutSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'My Orders';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="product-out-index adwrapper">

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

	<div class="panel panel-primary">
		<div class="panel-heading">  
		<h3 class="panel-title">
			<?= Html::encode($this->title) ?>
		</h3>
		<div class="clearfix"></div>
		</div>
	</div>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
   //     'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

           // 'id',
           [
			 'header' => 'Buyer',
			 'attribute' => 'buyer_user_id',
			 'value' => 'buyerUser.username',
			 'headerOptions' => ['style'=>'color: #428bca;'],
			],   
           // 'seller_user_id',
			[
			 'header' => 'Product Type',
			 'attribute' => 'product_type_id',
			 'value' => 'producttype.name',
			 'headerOptions' => ['style'=>'color: #428bca;'],
			],
			[
			 'header' => 'Potency',
			 'attribute' => 'potency_id',
			 'value' => 'potency.name',
			 'headerOptions' => ['style'=>'color: #428bca;'],
			],
			[
			 'header' => 'Quantity Type',
			 'attribute' => 'quantity_type_id',
			 'value' => 'quantitytype.name',
			 'headerOptions' => ['style'=>'color: #428bca;'],
			],	
			[
			 'header' => 'Product',
			 'attribute' => 'product_id',
			 'value' => 'product.name',
			 'headerOptions' => ['style'=>'color: #428bca;'],
			],
            'total_qty',
            'notes:ntext',
			
            //'status',
            'date_time',
            [
				'attribute' => 'status',
				'format' => 'raw',
				'value' => function ($model) {
					$status=null;
					if($model->status==1) $status = 'Order Created';
					if($model->status==2) $status = 'Order shipped';
					if($model->status==3) $status = 'Order Received';
					return $status;
				},
			],
            [
				'class' => 'yii\grid\ActionColumn',
				'template' => '{updateorder}', 
				'buttons'  => [
					'updateorder'   => function ($url, $model ) {
							$url = Url::to(['/productin/create', 'poutid' => $model->id]);
							return Html::a('Mark As Received', $url, ['class'=>'btn','title' => 'Convert Order']);
					},
				],

			],
        ],
    ]); ?>
</div>

views/productout/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\ProductOut */

$this->title = 'Create Product Out';
$this->params['breadcrumbs'][] = ['label' => 'Product Outs', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="product-out-create adwrapper">

	<div class="panel panel-primary">
		<div class="panel-heading">  
		<h3 class="panel-title">
			<?= Html::encode($this->title) ?>
		</h3>
		<div class="clearfix"></div>
		</div>
	</div>
	
    <?= $this->render('_form', [
        'model' => $model,
		'indent' => $indent,
    ]) ?>

</div>

views/productout/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\ProductOutSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Product Outs';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="product-out-index adwrapper">

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

	<div class="panel panel-primary">
		<div class="panel-heading">  
		<h3 class="panel-title">
			<?= Html::encode($this->title) ?>
		</h3>
		<div class="clearfix"></div>
		</div>
	</div>
	
	<?php
	$button=true;
	if(Yii::$app->user->identity->is_admin==1){
		$button=false;
	}
	?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
  //      'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

           // 'id',
           [
			 'header' => 'Buyer',
			 'attribute' => 'buyer_user_id',
			 'value' => 'buyerUser.username',
			 'headerOptions' => ['style'=>'color: #428bca;'],
			],   
           // 'seller_user_id',
			[
			 'header' => 'Product Type',
			 'attribute' => 'product_type_id',
			 'value' => 'producttype.name',
			 'headerOptions' => ['style'=>'color: #428bca;'],
			],
			[
			 'header' => 'Potency',
			 'attribute' => 'potency_id',
			 'value' => 'potency.name',
			 'headerOptions' => ['style'=>'color: #428bca;'],
			],
			[
			 'header' => 'Quantity Type',
			 'attribute' => 'quantity_type_id',
			 'value' => 'quantitytype.name',
			 'headerOptions' => ['style'=>'color: #428bca;'],
			],	
			[
			 'header' => 'Product',
			 'attribute' => 'product_id',
			 'value' => 'product.name',
			 'headerOptions' => ['style'=>'color: #428bca;'],
			],
            'total_qty',
            'notes:ntext',
			
            //'status',
            'date_time',
            [
				'attribute' => 'status',
				'format' => 'raw',
				'value' => function ($model) {
					$status=null;
					if($model->status==1) $status = 'Order Created';
					if($model->status==2) $status = 'Order shipped';
					if($model->status==3) $status = 'Order Received';
					return $status;
				},
			],
            [
				'class' => 'yii\grid\ActionColumn',
				'template' => '{delete}{update}', 
				'visible' => $button,
			],
        ],
    ]); ?>
</div>

views/productout/sindex.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\ProductOutSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'My Orders';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="product-out-index adwrapper">

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
	<div class="pull-right">
		<?= Html::a('Place Direct Order', ['create'], ['class' => 'btn btn-success','style'=>'float: right;']) ?>
	</div>
	<div class="clearfix"></div>
	
	<div class="panel panel-primary">
		<div class="panel-heading">  
		<h3 class="panel-title">
			<?= Html::encode($this->title) ?>
		</h3>
		<div class="clearfix"></div>
		</div>
	</div>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
  //      'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

           // 'id',
           [
			 'header' => 'Buyer',
			 'attribute' => 'buyer_user_id',
			 'value' => 'buyerUser.username',
			 'headerOptions' => ['style'=>'color: #428bca;'],
			],   
           // 'seller_user_id',
			[
			 'header' => 'Product Type',
			 'attribute' => 'product_type_id',
			 'value' => 'producttype.name',
			 'headerOptions' => ['style'=>'color: #428bca;'],
			],
			[
			 'header' => 'Potency',
			 'attribute' => 'potency_id',
			 'value' => 'potency.name',
			 'headerOptions' => ['style'=>'color: #428bca;'],
			],
			[
			 'header' => 'Quantity Type',
			 'attribute' => 'quantity_type_id',
			 'value' => 'quantitytype.name',
			 'headerOptions' => ['style'=>'color: #428bca;'],
			],	
			[
			 'header' => 'Product',
			 'attribute' => 'product_id',
			 'value' => 'product.name',
			 'headerOptions' => ['style'=>'color: #428bca;'],
			],
            'total_qty',
            'notes:ntext',
			
            //'status',
            'date_time',
            [
				'attribute' => 'status',
				'format' => 'raw',
				'value' => function ($model) {
					$status=null;
					if($model->status==1) $status = 'Order Created';
					if($model->status==2) $status = 'Order shipped';
					if($model->status==3) $status = 'Order Received';
					return $status;
				},
			],
            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

views/productout/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\ProductOut */

$this->title = 'Update Order';
$this->params['breadcrumbs'][] = ['label' => 'Product Outs', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="product-out-update adwrapper">

	<div class="panel panel-primary">
		<div class="panel-heading">  
		<h3 class="panel-title">
			<?= Html::encode($this->title) ?>
		</h3>
		<div class="clearfix"></div>
		</div>
	</div>
	
    <?= $this->render('_form', [
        'model' => $model,
        'indent' => $indent,
    ]) ?>

</div>

views/productout/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\ProductOut */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Product Outs', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="product-out-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'buyer_user_id',
            'seller_user_id',
            'product_type_id',
            'potency_id',
            'quantity_type_id',
            'product_id',
            'total_qty',
            'notes:ntext',
            'status',
            'date_time',
        ],
    ]) ?>

</div>