models/Indent.php
<?php

namespace app\models;

use Yii;
use app\models\QuantityType;
use app\models\ProductType;
use app\models\Potency;
use app\models\Product;
use app\modules\users\models\Users;
/**
 * This is the model class for table "indent".
 *
 * @property int $id
 * @property int $buyer_user_id indent user id
 * @property int $seller_user_id
 * @property int $product_type_id
 * @property int $potency_id
 * @property int $quantity_type_id
 * @property int $product_id
 * @property int $total_qty
 * @property string $notes
 * @property int $status
 * @property string $date_time
 */
class Indent extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'indent';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['buyer_user_id','seller_user_id', 'product_type_id', 'potency_id', 'quantity_type_id', 'product_id', 'total_qty'], 'required'],
            [['seller_user_id', 'product_type_id', 'potency_id', 'quantity_type_id', 'product_id', 'total_qty'], 'integer'],
            [['notes'], 'string'],
            [['date_time'], 'safe'],
            [['total_qty'], 'string', 'max' => 1],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'buyer_user_id' => 'Buyer User',
            'seller_user_id' => 'Seller User',
            'product_type_id' => 'Product Type',
            'potency_id' => 'Potency',
            'quantity_type_id' => 'Quantity Type',
            'product_id' => 'Product',
            'total_qty' => 'Total Qty',
            'notes' => 'Notes (Optional)',
            'status' => 'Status',
            'date_time' => 'Date Time',
        ];
    }
	
    public function getBuyerUser()
    {
        return $this->hasOne(Users::className(), ['id' => 'buyer_user_id']);
    }	
	
    public function getSellerUser()
    {
        return $this->hasOne(Users::className(), ['id' => 'seller_user_id']);
    }  
	
    public function getPotency()
    {
        return $this->hasOne(Potency::className(), ['id' => 'potency_id']);
    }
		
    public function getProducttype()
    {
        return $this->hasOne(ProductType::className(), ['id' => 'product_type_id']);
    }
		
    public function getQuantitytype()
    {
        return $this->hasOne(QuantityType::className(), ['id' => 'quantity_type_id']);
    }		
	
    public function getProduct()
    {
        return $this->hasOne(Product::className(), ['id' => 'product_id']);
    }
	
}

models/Inspection.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "inspection".
 *
 * @property int $id
 * @property string $title
 * @property string $date_of_inspection
 * @property string $column_included column included in inspection
 * @property string $start_date
 * @property string $end_date
 * @property string $date_time
 */
class Inspection extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'inspection';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title','buyer_user_id', 'date_of_inspection', 'column_included', 'start_date', 'end_date'], 'required'],
            [['id'], 'integer'],
            [['date_time'], 'safe'],
            [['date_of_inspection', 'start_date', 'end_date'], 'string', 'max' => 255],
            [['id'], 'unique'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'buyer_user_id' => 'Inspection For',
            'date_of_inspection' => 'Date Of Inspection',
            'column_included' => 'Column For Inspection',
            'start_date' => 'Start Date',
            'end_date' => 'End Date',
            'date_time' => 'Date Time',
        ];
    }
}

controllers/InspectionController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Inspection;
use app\models\InspectionSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Json;
use app\models\ProductIn;
use kartik\mpdf\Pdf;

/**
 * InspectionController implements the CRUD actions for Inspection model.
 */
class InspectionController extends Controller
{
	public $enableCsrfValidation = false;
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Inspection models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new InspectionSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Inspection model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
		
		$ProductIn = ProductIn::find()->all();

		$content = $this->renderPartial('view', [
					'model' => $this->findModel($id),
					'ProductIn' => $ProductIn,
				]);
		
		// setup kartik\mpdf\Pdf component
		$pdf = new Pdf([
			// set to use core fonts only
		//	'mode' => Pdf::MODE_CORE, 
			// A4 paper format
			'format' => Pdf::FORMAT_A4, 
			// portrait orientation
			'orientation' => Pdf::ORIENT_PORTRAIT, 
			// stream to browser inline
			'destination' => Pdf::DEST_BROWSER, 
			// your html content input
			'content' => $content,  
			// format content from your own css file if needed or use the
			// enhanced bootstrap css built by Krajee for mPDF formatting 
			'cssFile' => '@vendor/kartik-v/yii2-mpdf/assets/kv-mpdf-bootstrap.min.css',
			// any css to be embedded if required
			'cssInline' => '
							table, th, td {
							   border: 1px solid black;
							}table {
								border-collapse: collapse;
							}', 
			 // set mPDF properties on the fly
			'options' => ['title' => 'Ashirvad'],
			 // call mPDF methods on the fly
			'methods' => [ 
				'SetHeader'=>['Ashirvad'], 
				'SetFooter'=>['{PAGENO}'],
			]
		]);
		
		// return the pdf output as per the destination setting
		return $pdf->render(); 
		
		
		
    }

    /**
     * Creates a new Inspection model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Inspection();

        if ($model->load(Yii::$app->request->post())) {
			$model->column_included=Json::encode($_POST['Inspection']['column_included']);

			if($model->save()){
				return $this->redirect(['index']);	
			}            
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Inspection model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Inspection model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Inspection model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Inspection the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Inspection::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/inspection/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\date\DatePicker;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use app\modules\users\models\Users;

/* @var $this yii\web\View */
/* @var $model app\models\Inspection */
/* @var $form yii\widgets\ActiveForm */
?>
<?php $column_included=[
						'name'=>'Name',
						'abbreviations'=>'Abbreviations',
						'date_of_purches'=>'Date Of Purchase',
						'purchase_qty'=>'Purchase QTY',
						'date_of_mfg'=>'Date Of Manufacturing',
						'issue_date'=>'Date Of Issue',
						'out_qty'=>'Out QTY',
						'balance'=>'Balance',
						]; ?>
<?php $buyer_user_id=ArrayHelper::map(Users::find()->andWhere(['or',['is_buyer_seller'=>1],['is_buyer_seller'=>3]])->orderBy('id')->asArray()->all(),'id', 'username');; ?>


<div class="inspection-form">

    <?php $form = ActiveForm::begin(); ?>
	 <div class="col-lg-8">
 
		<?= $form->field($model, 'buyer_user_id')->widget(Select2::classname(), [
			'data' => $buyer_user_id,
			'options' => ['placeholder' => 'Select Buyer ...'],
			'pluginOptions' => [
				'allowClear' => true
			],
		]); ?>
	 
		<?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>
			
		<?= $form->field($model, 'column_included')->widget(Select2::classname(), [
			'data' => $column_included,
			'options' => ['placeholder' => 'Select Potency ...','id' => 'potency_id', 'multiple' => true],
			'pluginOptions' => [
				'allowClear' => true
			],
		]); ?>
			
		<?php  $date_of_inspection=null; if($model->date_of_inspection!=null){ $date_of_inspection=date('d-M-yy',strtotime($model->date_of_inspection)); }  ?>
		<?= $form->field($model, 'date_of_inspection')->widget(DatePicker::classname(), [
			'options' => ['value' => $date_of_inspection ,'placeholder' => 'Enter Date Of Inspection ...'],
			'pluginOptions' => [
				'autoclose'=>true,
				'format' => 'dd-M-yyyy',
				'todayHighlight' => true,
				'startDate' => date('d-m-Y h:i:s'),
			]
		]); ?>

		<?php  $start_date=null; if($model->start_date!=null){ $start_date=date('d-M-yy',strtotime($model->start_date)); }  ?>
		<?= $form->field($model, 'start_date')->widget(DatePicker::classname(), [
			'options' => ['value' => $start_date ,'placeholder' => 'Enter Date Of Inspection Start ...'],
			'pluginOptions' => [
				'autoclose'=>true,
				'format' => 'dd-M-yyyy',
				'todayHighlight' => true,
			]
		]); ?>
			
		<?php  $end_date=null; if($model->end_date!=null){ $end_date=date('d-M-yy',strtotime($model->end_date)); }  ?>
		<?= $form->field($model, 'end_date')->widget(DatePicker::classname(), [
			'options' => ['value' => $end_date ,'placeholder' => 'Enter Date Of Inspection End ...'],
			'pluginOptions' => [
				'autoclose'=>true,
				'format' => 'dd-M-yyyy',
				'todayHighlight' => true,
			]
		]); ?>
			
		<div class="form-group">
			<?= Html::submitButton('Download', ['class' => 'btn btn-success']) ?>
		</div>
	</div>
    <?php ActiveForm::end(); ?>

</div>

views/inspection/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\InspectionSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="inspection-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'date_of_inspection') ?>

    <?= $form->field($model, 'column_included') ?>

    <?= $form->field($model, 'start_date') ?>

    <?php // echo $form->field($model, 'end_date') ?>

    <?php // echo $form->field($model, 'date_time') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/inspection/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Inspection */

$this->title = 'Create Inspection';
$this->params['breadcrumbs'][] = ['label' => 'Inspections', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="inspection-create adwrapper">

	<div class="panel panel-primary">
		<div class="panel-heading">  
		<h3 class="panel-title">
			<?= Html::encode($this->title) ?>
		</h3>
		<div class="clearfix"></div>
		</div>
	</div>

	
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/inspection/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\InspectionSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Inspections';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="inspection-index adwrapper">

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

	<div class="pull-right">
		 <?= Html::a('Download Inspection', ['create'], ['class' => 'btn btn-success']) ?>
	</div>
	<div class="clearfix"></div>
	<div class="panel panel-primary">
		<div class="panel-heading">  
		<h3 class="panel-title">
			<?= Html::encode($this->title) ?>
		</h3>
		<div class="clearfix"></div>
		</div>
	</div>
	
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
       // 'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

           // 'id',
            'title',
            'date_of_inspection',
           // 'column_included',
            'start_date',
            'end_date',
            //'date_time',

            [
				'class' => 'yii\grid\ActionColumn',
				'template' => '{delete}{printinspection}', 
				'buttons'  => [
					'printinspection'   => function ($url, $model ) {
							$url = Url::to(['/inspection/view', 'id' => $model->id]);
							return Html::a('Print Inspection', $url, ['class'=>'btn','style'=>'margin: 0 10px;','target'=>'_blank','title' => 'Print Inspection']);
					},
				],

			],
        ],
    ]); ?>
</div>

views/inspection/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Inspection */

$this->title = 'Update Inspection: {nameAttribute}';
$this->params['breadcrumbs'][] = ['label' => 'Inspections', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="inspection-update adwrapper">

	<div class="panel panel-primary">
		<div class="panel-heading">  
		<h3 class="panel-title">
			<?= Html::encode($this->title) ?>
		</h3>
		<div class="clearfix"></div>
		</div>
	</div>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/inspection/view.php
<?php

use yii\helpers\Html;
use yii\helpers\Json;
use yii\widgets\DetailView;
use app\models\ProductIn;

/* @var $this yii\web\View */
/* @var $model app\models\Inspection */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Inspections', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

$buyer_user_id=null;
$title=null;
$date_of_inspection=null;
$column_included=null;
$start_date=null;
$end_date=null;

$buyer_user_id=$model->buyer_user_id;
$title=$model->title;
$date_of_inspection=$model->date_of_inspection;
$column_included=$model->column_included;
$start_date=date('Y-m-d',strtotime($model->start_date));
$end_date=date('Y-m-d',strtotime($model->end_date));


$productins = ProductIn::find()
			 ->where(['between', 'date_time', $start_date, $end_date])
			 ->andWhere(['=', 'buyer_user_id', $buyer_user_id])
			 ->all();

if(count($productins)>0){

?>

<?php $column_included=[
						'name'=>'Name',
						'abbreviations'=>'Abbreviations',
						'date_of_purches'=>'Date Of Purchase',
						'purchase_qty'=>'Purchase QTY',
						'date_of_mfg'=>'Date Of Manufacturing',
						'issue_date'=>'Date Of Issue',
						'out_qty'=>'Out QTY',
						'balance'=>'Balance',
						]; ?>
						
						
	<div class="inspection-view">

		<h1><?= Html::encode($this->title) ?></h1>

	<table style="width:100%">
	  <tr>
		<?php
		
		$column_includeds=Json::decode($model->column_included);

		if($column_includeds!=null){
			foreach($column_includeds as $columnname){
			?>
				<th><?php echo $column_included[$columnname]; ?></th>
			<?php } ?>
		<?php } ?>
	  </tr>
	  
	  <?php foreach($productins as $productin){

			  $total_in=0; 
			  $total_out=0; 
			  $total_in=$productin->total_qty; 
			  $total_out=$productin->productOut->total_qty;
			  $balance=$total_in-$total_out;

	  ?>
	  <tr>
		<?php if(in_array('name',$column_includeds)){ ?><td><?php echo $productin->product->name; ?></td><?php } ?>
		<?php if(in_array('abbreviations',$column_includeds)){ ?><td><?php echo $productin->product->abbreviations; ?></td><?php } ?>
		<?php if(in_array('date_of_purches',$column_includeds)){ ?><td><?php echo $productin->date_of_purchase; ?></td> <?php } ?>
		<?php if(in_array('purchase_qty',$column_includeds)){ ?><td><?php echo $total_in; ?></td> <?php } ?>
		<?php if(in_array('date_of_mfg',$column_includeds)){ ?><td><?php echo $productin->date_of_mfg; ?></td> <?php } ?>
		<?php if(in_array('issue_date',$column_includeds)){ ?><td><?php echo $productin->issue_date; ?></td> <?php } ?>
		<?php if(in_array('out_qty',$column_includeds)){ ?><td><?php echo $total_out; ?></td> <?php } ?>
		<?php if(in_array('balance',$column_includeds)){ ?><td><?php echo $balance; ?></td> <?php } ?>
	  </tr>
	  <?php } ?>

	</table>

	</div>
<?php }else{ ?>
	<div class="inspection-view">
	 No record Found.
	</div>
<?php } ?>